[package]
authors = ["Justin Charette <charetjc@gmail.com>"]
name = "neovim-scorched-earth"
version = "0.1.0"

[dependencies]
log = "0.3.7"
simplelog = "0.4.2"

[dependencies.neovim-lib]
git = "https://github.com/daa84/neovim-lib.git"
rev = "e3e7e2a5dc44acf56d199ee70581978f00266022"
